services:
  minio1:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIOUSER}
      MINIO_ROOT_PASSWORD: ${MINIOPASSWORD}
    volumes:
      - minio-data:/data
    command: "server /data --console-address :9001"

  spamer:
    build:
      context: .
      dockerfile: spamer.dockerfile
    env_file:
      - .env

volumes:
  minio-data:
    driver: local
    driver_opts:
      o: size=10m
      device: tmpfs
      type: tmpfs
